### ISSUE TITLE
https请求无法代理

### ISSUE THREAD

**Issue by tallongsun** [sheepbao/gomitmproxy#15]
启动gomitmproxy，配置chrome使用代理http://localhost:8080，http请求正常，但对于https请求，比如https://www.baidu.com，chrome报错NET::ERR_CERT_AUTHORITY_INVALID
![image](https://user-images.githubusercontent.com/7836739/36980159-7f5c6b26-20c4-11e8-860a-915b5a7a82fe.png)

**Comment by zboya** [comment]
给你的chrome浏览器添加自签名的证书gomitmproxy-ca-cert.pem
