### ISSUE TITLE
这个包对于http隧道是怎么处理的呢？

### ISSUE THREAD

**Issue by shellus** [sheepbao/gomitmproxy#16]
例如用这个包开一个http代理。
那么curl用这个代理去请求一个https网址的之后，会发送一个HTTP CONNECT请求和源站建立透明隧道。
这个包能劫持这种情况吗？

**Comment by zboya** [comment]
可以的，这种情况就是gomitmproxy作为中间人，对于curl来说它是服务端，对于https网站来说它是客户端，但是一定要添加自签名证书到电脑里为根证书。
