### ISSUE TITLE
不知道为什么，我用时总有这样的issues.但也可以用，只是速度不与直接上网快

### ISSUE THREAD

**Issue by zytzjx** [sheepbao/gomitmproxy#2]
[gomitmproxy]2016/06/21 13:51:40 /root/gocode/src/github.com/gomitmproxy/gomitmproxy.go:116: readRequest err: EOF
[gomitmproxy]2016/06/21 13:51:40 /root/gocode/src/github.com/gomitmproxy/gomitmproxy.go:116: readRequest err: EOF
[gomitmproxy]2016/06/21 13:51:40 /root/gocode/src/github.com/gomitmproxy/gomitmproxy.go:116: readRequest err: EOF
[gomitmproxy]2016/06/21 13:51:40 /root/gocode/src/github.com/gomitmproxy/gomitmproxy.go:116: readRequest err: EOF
[gomitmproxy]2016/06/21 13:51:40 /root/gocode/src/github.com/gomitmproxy/gomitmproxy.go:116: readRequest err: EOF
[gomitmproxy]2016/06/21 13:51:40 /root/gocode/src/github.com/gomitmproxy/gomitmproxy.go:116: readRequest err: EOF
[gomitmproxy]2016/06/21 13:51:40 /root/gocode/src/github.com/gomitmproxy/gomitmproxy.go:116: readRequest err: EOF
[gomitmproxy]2016/06/21 13:51:40 /root/gocode/src/github.com/gomitmproxy/gomitmproxy.go:116: readRequest err: EOF

**Comment by zboya** [comment]
EOF表示文件结尾，一般是客户端主动close了socket引起的，表示io已经读到文件结尾了，总之谢谢指出，我加个判断就好了。至于网速变慢的原因我也在找，目前正在弄CA的实现。
