### ISSUE TITLE
"listome.com/log"  未包含

### ISSUE THREAD

**Issue by wwek** [sheepbao/gomitmproxy#5]
"listome.com/log" 

go build
genKey.go:17:2: cannot find package "listome.com/log" in any of:
        C:\Go\src\listome.com\log (from $GOROOT)
        D:\Project\go\src\listome.com\log (from $GOPATH)

不能build

**Comment by zboya** [comment]
谢谢指出，我已经改了，是sublime保存时自动添加的，有任何问题继续提问
