### ISSUE TITLE
connection problem

### ISSUE THREAD

**Issue by zytzjx** [sheepbao/gomitmproxy#6]
我安装了gomitmproxy,没有任何命令行参数.
2016/07/11 16:09:43 proxy listening port:8080
2016/07/11 16:09:43 ListenAndServe
2016/07/11 16:13:30 http: TLS handshake error from 10.1.1.129:56117: EOF

用手机通过这个代理上网。手机上会出现Connection Problem
this page contains too many server redirects.

**Comment by zboya** [comment]
谢谢反馈，如果是要代理上https的网站，需要把gomitmproxy-ca-cert.pem安装到设备上：
1. .iOS上安装
　　将gomitmproxy-ca-cert.pem发送到iphone邮箱里，通过浏览器访问/邮件附件
2. Android上安装
　　将gomitmproxy-ca-cert.pem改为gomitmproxy-ca-cert.cer 放到sdcard根目录下
　　选择设置-安全和隐私-从存储设备安装证书

如有问题希望继续提出。

**Comment by zboya** [comment]
更新了代码，已经测试了，我这边没问题

**Comment by luckypoem** [comment]
hi.

yudeMacBook-Air:gomitmproxy brite$ 2016/10/04 18:35:47 trans error  read tcp 127.0.0.1:3080->127.0.0.1:60682: read tcp 192.168.1.103:60683->my_vps_ip:9999: read: connection reset by peer

我在linux vps和mac上都安装了gomitmproxy,但在mac上运行；
./gomitmproxy -port 3080 -raddr my_vps_ip:9999却出现如上提示，是因为未装证书gomitmproxy-ca-cert.pem到mac上的缘故吗？看了这里 https://support.apple.com/kb/PH7297?locale=zh_CN&viewlocale=zh_CN ，但不知钥匙串在哪里？

谢谢回复！
