### ISSUE TITLE
怎么获取服务器ip？

### ISSUE THREAD

**Issue by lf2186** [sheepbao/gomitmproxy#7]
代理模式下，怎么获取 请求页面服务器的ip地址？

**Comment by zboya** [comment]
不太明白你的意思，比如，客户端用gomitmproxy代理请求www.baidu.com，你是需要知道www.baidu.com的ip地址，还是说要知道客户端的地址？

**Comment by lf2186** [comment]
比如，通过代理访问 www.baidu.com ，要获取 请求www.baidu.com的ip地址（RemoteAddr）

**Comment by zboya** [comment]
这个没加，要加也很简单就是了，等会加

**Comment by zboya** [comment]
已经加上了
