### ISSUE TITLE
获取网站服务器地址

### ISSUE THREAD

**Issue by lf2186** [sheepbao/gomitmproxy#8]
dump.go添加：fmt.Printf("%s %s\n", Blue("RemoteAddr:"), req.RemoteAddr)
获取的ip不对的，如果本机是代理，ip获取出来是127.0.0.1，你试试。。
Request:
GET  http://www.baidu.com/ <--200
RemoteAddr: 127.0.0.1:51647
User-Agent: [curl/7.43.0]
Accept: [_/_]
Connection: [Keep-Alive]
Response:
Server: [BWS/1.1]
Content-Type: [text/html; charset=utf-8]
Connection: [Keep-Alive]
Vary: [Accept-Encoding]

**Comment by zboya** [comment]
是啊，本机的代理，当然是127.0.0.1 ，难道你的意思是要获取www.baidu.com 的ip？

**Comment by zboya** [comment]
如果你要获取www.baidu.com 的ip，直接ping www.baidu.com 不就好了

**Comment by lf2186** [comment]
常用的代理抓包工具，比如fiddler／burp／owasp 等，都有这个功能。www.baidu.com可能会有多个ip，ping出来的ip和http请求时的ip，不一定一样。假如抓包，想看哪个ip的服务器返回的数据有问题，久需要这功能了。

**Comment by zboya** [comment]
很感谢提出，我会在后续中加这个功能
